name: Aaron Gilmore
markdown: redcarpet
pygments: true

# Site settings
description: ""
twitter: ""
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://wip.theinternetisfor.info"
# url: "http://localhost:4000"
url: "http://aarongilmore.com" # the base hostname & protocol for your site
twitter_username: aarondgilmore
github_username:  aarongilmore
timezone: "Europe/London"
permalink: /:title/
author:
  name: Aaron Gilmore
  email: aaron@aarongilmore.com


paginate: 10
paginate_path: "/journal/page/:num/"

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Projects
    url: /projects/
  - title: Github
    url: https://github.com/aarongilmore
    external: true
  - title: Twitter
    url: https://twitter.com/aarondgilmore
    external: true
  - title: RSS
    url: /feed.xml
