title: Aaron Gilmore | Designer
name: Aaron Gilmore
highlighter: true
encoding: utf-8

# Site settings
description: "My name is Aaron and I design and build websites with a focus on functional interaction design, good typography, speed, and simplicity."
twitter: "Designing and building for the web, drinking coffee, travelling."
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://wip.theinternetisfor.info"
# url: "http://localhost:4000"
url: "http://aarongilmore.com/" # the base hostname & protocol for your site
twitter_username: aarondgilmore
github_username:  aarongilmore
timezone: "Europe/London"
permalink: /writing/2009/04/29/slap-chop/
author:
  name: Aaron Gilmore
  email: aaron@aarongilmore.com

# Build settings
markdown: kramdown
highlighter: rouge

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: _scss
  style: :compressed

exclude: ['Gemfile','Gemfile.lock']
